name: CI

on:
  pull_request:
    branches: [dev, stg, prd]
    types: [opened, reopened, synchronize, edited]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
env:
  tofu_version: "1.8.0" # must satisfy iac/app/main.tf and iac/setup/setup.tf

jobs:
  env:
    name: Set Env Vars
    timeout-minutes: 1
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up DEV Environment Variables
        if: github.base_ref == 'dev'
        run: |
          matrix='{
            "env":[
              {
                "environment_name":"dev",
                "tf_working_dir":"./iac/app",
                "tf_var_file":"dev.tfvars",
                "aws_account":"977306314792",
                "aws_gha_role":"hw-static-site-dev-gha"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

      - name: Set up STG Environment Variables
        if: github.base_ref == 'stg'
        run: |
          matrix='{
            "env":[
              {
                "environment_name":"stg",
                "tf_working_dir":"./iac/app",
                "tf_var_file":"stg.tfvars",
                "aws_account":"977306314792",
                "aws_gha_role":"hw-static-site-stg-gha"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

      - name: Set up PRD/CPY Environment Variables
        if: github.base_ref == 'prd'
        run: |
          matrix='{
            "env":[
              {
                "environment_name":"prd",
                "tf_working_dir":"./iac/app",
                "tf_var_file":"prd.tfvars",
                "aws_account":"539738229445",
                "aws_gha_role":"hw-static-site-prd-gha"
              },
              {
                "environment_name":"cpy",
                "tf_working_dir":"./iac/app",
                "tf_var_file":"cpy.tfvars",
                "aws_account":"539738229445",
                "aws_gha_role":"hw-static-site-cpy-gha"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

    outputs:
      matrix: ${{ env.matrix }}

  # TODO: Add jobs to build and test website code

  format:
    name: Tofu Format
    timeout-minutes: 3
    runs-on: ubuntu-latest
    needs: env
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
      fail-fast: false
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: OpenTofu Setup
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.tofu_version }}

      - name: OpenTofu Format
        working-directory: "./"
        run: tofu fmt -check -recursive

  plan:
    name: Tofu Plan / ${{ matrix.env.environment_name }}
    timeout-minutes: 6
    runs-on: ubuntu-latest
    needs: env
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
      fail-fast: false
    permissions:
      contents: read
      actions: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: "arn:aws:iam::${{ matrix.env.aws_account }}:role/${{ matrix.env.aws_gha_role }}"
          role-session-name: ${{ github.sha }}
          aws-region: us-west-2

      - name: OpenTofu Setup
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.tofu_version }}

      - name: OpenTofu Init
        working-directory: ${{ matrix.env.tf_working_dir }}
        run: tofu init -var-file=${{ matrix.env.tf_var_file }}

      - name: OpenTofu Plan
        working-directory: ${{ matrix.env.tf_working_dir }}
        run: tofu plan -input=false -out=plan -lock=false -var-file=${{ matrix.env.tf_var_file }}

      - name: Comment Terraform Plan
        uses: byu-oit/github-action-tf-plan-comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ matrix.env.tf_working_dir }}
          terraform-plan-file: plan

      - name: Analyze Terraform Plan
        uses: byu-oit/github-action-tf-plan-analyzer@v2
        with:
          working-directory: ${{ matrix.env.tf_working_dir }}
          terraform-plan-file: plan
          divvycloud-username: ${{ secrets.DIVVYCLOUD_USERNAME }}
          divvycloud-password: ${{ secrets.DIVVYCLOUD_PASSWORD }}
